### ISSUE TITLE
x(N) not placing scaled element at N pixels on the X axis

### ISSUE THREAD

**Issue by nolazybits** [wout/svg.js#381] opened 2015-09-10 05:13 UTC
I am working on a group that I scale, and then move.

In the previous version, the group will behave as wanted (i.e x(N) will place my group on the X axis at N pixels)
Now the group is not placed at N pixel if it has a scale but N*scale.
I have check the code and documentation a bit and it seems this is a feature that is enabled with the relative = true flag which is enabled by default.

How could I have my group being set properly on the x axis using the x(N) method.
I am also using the svg.draggable.js library to drag those groups.

Regards,
Xavier

**Comment by nolazybits** [comment] 2015-09-14 00:07
Anyone?

**Comment by Fuzzyma** [comment] 2015-09-14 07:32
There *was* a more or less feature which normalized the movement of scaled elements.
However this behavior was not consistent. It worked not everywhere.

If you thin about it, it was the wrong behavior because it was magic. If you have a scaled element (2x) and you move an element 100px it is moved 200px on the screen which is the right behavior.
Only moving it 100px would move it only 50px in *its* world. And here comes the problem:
Every transformed element lifes in its own coordinate system. You always move the element in their system and **not** in the coordinate system of the screen.

If you want to transform the movement from the screen coords to the elements coords you would have to use `createSVGPoint` and `matrixTransform` which is used e.g. in the draggable or draw-plugin.

However with svg.draggable.js there should be no problem with dragging transformed elements

**Comment by nolazybits** [comment] 2015-09-14 23:31
Well I move the element on its parent coord system right? And the parent is not scaled, so why would the element moved scale*x?
The thing is the behavior changed (or a bug introduced) from 1.1.0 to 2.x and I'm trying to understand where so I could fix it, but had no luck so far.

Using the svg.draggable.js on the element is also problematic (it doesn't follow the mouse position)

Any ideas?
If it helps I could try to create an example showing the behavior.

Thanks @Fuzzyma

**Comment by Fuzzyma** [comment] 2015-09-15 07:42
yes. the behavior changed. New versions bring breaking changes ^^.
No you dont move it in the parent coord system. As soon as you apply transformations the element gets its own coordinate system. Its easier to understand when you imagine that not the element itself is transformed but its coordinate system is. The transformation of the element is only a consequenze of the transformation of the coordinate system.
Anyway - a fiddle is always a good thing

**Comment by nolazybits** [comment] 2015-09-15 12:29
I have created a jsfiddle from memory. I could try to get some code out of our current tool to have something closer.
On the fiddle there is a weird behavior (even when not scaling the thumb, where if you move the mouse up or down when dragging the Y coordinate changes even though constraint on Y -15).
When you scale it moves the circle way out of place. I understand what you said above but I don't think it is a natural behavior to move the element. It would make sense if the parent would have been scaled; as I understand relative coordinate system, relative to my parent, which is **already** the case, i.e in  the example positioning the line and rectangles are relative to the group coordinate.

I will try to get something tomorrow for me to show the weird dragging behavior.

Thanks again a lot looking into this @Fuzzyma

**Comment by Fuzzyma** [comment] 2015-09-15 16:12
At first sight I saw a few problems in your code which leads to trouble:

 - the constraints are not checking for the center of an element. They check the bounding box of the element. Giving a constraint from -15 to -15 (which means nothing), leads to unexpected behavior. Give the element some air to stay somewhere.
If you want the circle to follow the -15px-line you should use your own function here instead of a constraint-**box**. (btw: This case is covered very well in the docs and in the example)

- you scale the element. Of course it changes the position because you scaled the whole coordinate system of the element. So every pixel is bigger now -> circle is moving.

When you comment out the constraint and the scale, dragging works as expected. Even if you reactivate the scale you see that it is jumping only once (when you scale it) but dragging works well (of course with offset but the offset is not changing. changing offset is what you would see, when dragging would not handle the scale)

**Closed** 2015-09-29 11:57 UTC
