### ISSUE TITLE
Pattern Rotation Animation

### ISSUE THREAD

**Issue by inluxc** [wout/svg.js#385] opened 2015-09-16 10:42 UTC
Ok, first of all sorry for being a pain the ass,  lol :D

The pattern rotation works fine, but not with animation i get the following error.

```
Uncaught TypeError: this.node.getCTM is not a function
SVG.Matrix.SVG.invent.construct.ctm @ svg.min.js:1915
SVG.FX.SVG.invent.extend.attr @ svg.min.js:1354
SVG.extend.transform @ svg.min.js:2120
SVG.extend.rotate @ svg.min.js:3815
mouseover @ site.js:311
(anonymous function) @ site.js:340
forEach.SVG.Element.(anonymous function).f.node.(anonymous function) @ svg.min.js:2327
```

**Comment by Fuzzyma** [comment] 2015-09-16 11:09
I always knew that this animation stuff will drive me crazy one time :D.
Can I see your code pls?

**Comment by inluxc** [comment] 2015-09-16 11:16
Its same thing like this.

```
var patternImg3 = draw.pattern(306, 81, function(add) {
            add.image(baseUrlmedia + 'product/image'+data.img);
        }).x(menu3Limite3-3).y(212);
var menu3Img = draw.polyline([[menu3Limite3-3, 212], [(menu3Limite3+220), 212], [(menu3Limite4+220), 293], [menu3Limite4-3, 293]]).fill(patternImg3);

var menu3Wrapper = draw.polyline([[menu3Limite2, 255], [0, 255], [0,170], [menu3Limite1, 170]])
            .fill({color: 'transparent'})
            .stroke({width: 0})
            .attr('id', 'menu3Wrapper');

menu3Wrapper.mouseover(function(){
     patternImg.animate().rotate(15);
});

```

**Comment by inluxc** [comment] 2015-10-02 14:47
Any news about this ticket????

Thanks..

**Comment by Fuzzyma** [comment] 2015-10-05 18:17
Nope sorry. I am very busy atm

**Comment by ibrierley** [comment] 2015-10-06 16:31
Not so familiar with svg.js, but as a hacky workaround for the time, could you just animate it manually with transform inside an animate 'during' function...eg something like this..

http://jsfiddle.net/32yxud2k/2/

```
myRect.animate(2000).during( rotatePattern );

function rotatePattern( val ) {
  pattern.transform({ rotation: val * 45 } )
}
```

**Comment by Fuzzyma** [comment] 2015-10-10 13:46
I fixed the problem but there is much more to do!
So lets talk about **user intended behavior**:
What do you think the following calls will/should do:

```javascript
element.animate().rotate(15).scale(2).rotate(50)
element.animate().rotate(15).rotate(15)
element.animate().scale(2).scale(2)   
```

And what do you think this ones will do:

```javascript
element.rotate(15).scale(2).rotate(50)
element.rotate(15).rotate(15)
element.scale(2).scale(2)   
```

That is very important for me to know! Meanwhile I will prepare the commit for this fix

**Comment by ibrierley** [comment] 2015-10-10 17:30
I don't know svg.js much, but quick thoughts...

Would it not make sense to make it equivalent to what would happen in svg, eg transform='rotate(15) scale(2) rotate(50)' (apart from the obvious differences like transform origin)..

animate is a bit fiddlier ? I guess you may want to animate the individual elements value each time (rather than interpolate the matrix).

**Comment by Fuzzyma** [comment] 2015-10-10 17:48
thx @ibrierley for your valuable thoughts!
What you say makes perfectly sense. I myself came to this point. Until now svg.js always set absolute values so if you scale, translate and scale again it will overwrite the first scale. There is a `relative`-flag to ovewrite this behavior but I strongly think it should be the other way round.

Animating stuff is difficult, yes. But its not the math which causes problems (in svg.js everything is done with matrix interpolation so that is not a thing).
You just dont know what a call to `element.animate().something()` will do to the element.
e.g.
 - should it animate TO the value given
 - should it animate BY the value given (so multiple calls will animate it further)

Its kinda the same problem (relative, absolute) and I feel like it should be relative, too. However rotational animation is hard to tame (when you interpolate a matrix you cannot define if clockwise or anticlockwise) and thats why there is an additonal parameter - but only one. So multiple calls to rotate in ONE animation chain will fail.

For me its important to know what the user THING it does just by looking on the function call.

**Comment by GrupoWebex** [comment] 2015-11-04 12:13
There is my custom solution with SnapSVG: http://jsfiddle.net/L7jgm7uu/
I try to implement on SVG.js with user suggestion here, without success: http://jsfiddle.net/reocL50v/6/

**Comment by ibrierley** [comment] 2015-11-04 12:13
I guess consistency is the key here, as peoples existing code (if I understand right, as mentioned not so familiar with svg.js yet) would default to 'TO', you probably don't want to change that and break stuff (sorry if I'm misunderstanding)?

Could you include a relative method...no idea if this would work, or if its a good idea ?

myrect.animate().relative().rotate(45)
myrect.animate().absolute().transform(20,20).relative().rotate(20)

**Comment by ibrierley** [comment] 2015-11-04 12:19
GrupoWebex, try http://jsfiddle.net/reocL50v/7/

I think its the version of svg.js on the original fiddle thats causing an extra issue.

**Comment by GrupoWebex** [comment] 2015-11-04 12:24
Frame definition and a defined function call should be great which can be a custom function or predefined function (on svg.js). 
But problem is not here, problem is animation (relative or absolute) is not working, so i think defined item get wrong update params on recursive animation.

**Comment by Fuzzyma** [comment] 2015-11-04 14:37
@GrupoWebex this issue aims to find a way to implement the animation in a proper way. The current implementation is broken but cant be fixed without thinking about the problem I mentioned here.
So its in the first place a discussion about the **user intended behavior** and not about fixing the problem in the first place

**Comment by ibrierley** [comment] 2015-11-04 15:05
Might also be worth clarifying, what is broken in the current implementation. Is something broken, or just not well understood/described (which is part of svg transforms in itself typically for most).

**Comment by ibrierley** [comment] 2015-11-04 16:33
Sorry for spam, another alternative maybe actually having rotateTo, rotateBy etc methods to remove any amiguity (and leave old original methods intact for compatibility).

**Comment by Fuzzyma** [comment] 2015-11-04 17:45
Whats broken:
Rotation doenst work in a correct manner. e.g. when you run several animations which should rotate the element by a certain degree it will first rotate in **one** direction but every other call will rotate in the **other** direction.
Example: https://jsfiddle.net/k37nuzLs/1/

Thats the most mentioned error I realized so far.
The problem with animated rotation is always the same. When you use matrices to rotate an element you can only rotate it in the range of 0-360°. As soon as the value is over 360 the element spins back. Thast the only reason we have a parameter which tracks rotation in the code. But as you can see it doenst work as it should.

I dont know if there are more errors with animations. However imo the animation-modul is quite confusing. The normal behavior should be relative since you are chaning the transformations.

The rotateTo/rotateBy methods would be a huge clarification. I just wanted to avoid this doubling for every transformation (even if its done for move, x and y, too (see dmove, dx, dy)).

**Comment by GrupoWebex** [comment] 2015-11-04 18:41
Direction on rotate should be implemented with +- number signs on deegres. That is perfect to not cause any confusion...

Queued animations hasn't any problem since after() + animate() delay option work well. Extra function for working more easy, will be good too.

**Comment by Fuzzyma** [comment] 2015-11-04 18:49
@GrupoWebex the implementation with +- would lead to LOTS OF confusing:

```javascript
el.rotate(45) // rotates to 45
el.rotate(+45) // does the same
el.rotate(-45) // rotates 45 back? or rotates to -45?
```

The value -45° is a valid and therefore you cant missuse it as indicator of the direction.
Its however common sense that the value is always animated in the `which one is higher` direction.
So 45 to 300 will always rotate the one way and 300 to 45 the other way round. If you want to rotate further you have to write 300 to 360 + 45 = 405 instead

**Comment by GrupoWebex** [comment] 2015-11-04 23:30
Maybe logic of (+-)number can be defined if you are on left or right from center (cx).
left to cx: positive go up, negative go down
right to cx: negative go up, positive go down

**Comment by ibrierley** [comment] 2015-11-05 12:24
Just thinking about intuition, not sure if this is a related bug, or I'm not using it right, but I would probably expect these two rects to be in the same place for example...the scale being ignored for the rotation is what I'm guessing. I note the order of transform doesn't seem to make any difference.

https://jsfiddle.net/k37nuzLs/9/

**Comment by GrupoWebex** [comment] 2015-11-05 13:09
i think it is a inline function problem.
Testing: https://jsfiddle.net/k37nuzLs/12/

**Comment by ibrierley** [comment] 2015-11-05 13:40
Oh yes, its probably as the inline version isn't scaling from the centre, and taking 0,0 I would imagine. Ignore me!

**Comment by Fuzzyma** [comment] 2015-11-05 13:59
looks like the relative flag gets ignored. I guess I have to rewrite the whole rotation thing...
I tested the rotation with 0,0 and its still is not the same.

@GrupoWebex: we are not d3 and we are not parsing strings to get transformation relative/absolute. Furtermore in your example I dont know if the rotation is relative or absolute either so it doenst seems that intuitive to me

**Comment by ibrierley** [comment] 2015-11-05 16:08
I'm wondering if its related to this bit of code...

     if (relative) {
//        o.rotation += this.param && this.param.rotation != null ?
//          this.param.rotation :
//          matrix.extract().rotation
      }

If I comment that out, it seems to work on rotations, but I'm not familiar enough with the code to know if thats needed for some reason elsewhere. Is that because is the rotation is being applied to the existing matrix anyway maybe, so doesn't need to be added there again ?

**Comment by Fuzzyma** [comment] 2015-11-05 16:23
Hm that could be a problem. Looks like you add the rotation to the already present rotation and rotate with this value instead of the right one. However the animation example still doesnt work

**Comment by ibrierley** [comment] 2015-11-05 17:10
I also note like 1850:

(this.param.to.rotation - this.param.from.rotation * 2) * pos

Any reason for the * 2 ?

That seems to help a bit with some oddness, but maybe still issues with
relativity.

Ian

**Closed** 2016-05-16 18:01 UTC
