### ISSUE TITLE
Moving cloned text nodes doesn't work horizontally

### ISSUE THREAD

**Issue by dhardtke** [wout/svg.js#369] opened 2015-08-08 12:30 UTC
Hey,

have a look at this: https://jsfiddle.net/w5zod1m3/6/

At first I thought it was a bug in svg.draggable.js, but it's not.

The tspan's x coordinate doesn't get updated.

**Comment by Fuzzyma** [comment] 2015-09-06 18:57
The problem is a bit more complex.
When positioning text, svg tries to rebuild the text whenever the position of the text is changed.
However the rebuildfunction is only activated, when the tspans are marked as newlines.
This is done when setting up text with `text()`. When you use `clone()` this setup does not happen. Thats why the `move()`-function wont move the text. **Note:** The x-attribute of the `text` is changed but the `tspan` has a x-attribute, too which resets the one of the text.

For a quickfix just call `.text('somestring')` to trigger the rebuild.
For a better fix the clone-function of the text-element has to be reworked

**Comment by erivas3649** [comment] 2015-11-04 12:48
This is still an issue on 2.1.1
```javascript
draw.svg(data.svg);			
draw.each(function(){
if(this.type == 'image' || this.type == 'text'){				  this.click(onMouseClick).mouseover(onMouseOver).mouseout(onMouseOut).draggable();
this.dragstart= onDragStart;
}
});
```
The text can only be dragged vertically, unless its content changes.

**Comment by Fuzzyma** [comment] 2015-11-04 13:09
Please try the very latest commit and check if the error remains

**Comment by erivas3649** [comment] 2015-11-04 13:21
Hi, im using this commit  28c8ded from 3 hours ago.

**Comment by Fuzzyma** [comment] 2015-11-04 13:27
this problem is related to https://github.com/wout/svg.js/issues/393#issuecomment-153545234
I will try to fix that in another way

**Comment by Fuzzyma** [comment] 2015-11-05 02:40
@erivas3649 when dragging text, the x-attr of the text is updated but not the one of the tspans.
When the data you imported is not from svg.js itself you should take care, that the x-attr of the tspans is not set. However `dx` is no problem and can be used instead.
This way the text can be dragged as expected.

When the data you used for import is exported from svg.js than the comment before applies

**Comment by erivas3649** [comment] 2015-11-05 18:21
The data im using for import is previously exported from svg.js.

After inserting a text with svg.js the x-atrr of tspans is asigned and is equal to the x-atrr of the text, this might be the issue.
```xml
<text fill="#000000" font-size="34" y="417.1999702453613" x="237" font-family="Arial, Helvetica, sans-serif" id="SvgjsText1054"><tspan x="237" dy="44.2" id="SvgjsTspan1058">INSERT TEXT HERE</tspan></text>
```

**Closed** 2015-11-06 21:08 UTC
